// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DistanceTests(arg1) {
  return window['go']['files']['DistanceTest']['DistanceTests'](arg1);
}
