// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function MaximizeUnmaximize():Promise<void>;

export function Minimize():Promise<void>;
