// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tabs} from '../models';

export function HistoryBack(arg1:tabs.Tab):Promise<void>;

export function HistoryForward(arg1:tabs.Tab):Promise<void>;

export function NewTab():Promise<tabs.Tab>;
