// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HistoryBack(arg1) {
  return window['go']['tabs']['Manager']['HistoryBack'](arg1);
}

export function HistoryForward(arg1) {
  return window['go']['tabs']['Manager']['HistoryForward'](arg1);
}

export function NewTab() {
  return window['go']['tabs']['Manager']['NewTab']();
}
