// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoSomething(arg1) {
  return window['go']['test']['SampleTest']['DoSomething'](arg1);
}
